In [42]:
import pandas as pd
import numpy as np
from pyod.models.iforest import IForest

In [43]:
data = pd.read_csv('..//database//api_data//api_data.csv')
data

,flight_date,flight_status,aircraft,live,departure_airport,departure_timezone,departure_iata,departure_icao,departure_terminal,departure_gate,...,flight_number,flight_iata,flight_icao,flight_codeshared,flight_codeshared_airline_name,flight_codeshared_airline_iata,flight_codeshared_airline_icao,flight_codeshared_flight_number,flight_codeshared_flight_iata,flight_codeshared_flight_icao
0,2025-07-06,scheduled,NaN,NaN,Tontouta,Pacific/Noumea,NOU,NWWW,NaN,NaN,...,740,5K740,HFY740,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-07-06,scheduled,NaN,NaN,Tontouta,Pacific/Noumea,NOU,NWWW,NaN,NaN,...,4022,AF4022,AFR4022,NaN,hi fly,5k,hfy,740.0,5k740,hfy740
2,2025-07-06,scheduled,NaN,NaN,Auckland International,Pacific/Auckland,AKL,NZAA,I,NaN,...,132,MH132,MAS132,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-07-06,scheduled,NaN,NaN,Auckland International,Pacific/Auckland,AKL,NZAA,I,NaN,...,5585,WY5585,OMA5585,NaN,malaysia airlines,mh,mas,132.0,mh132,mas132
4,2025-07-06,scheduled,NaN,NaN,Auckland International,Pacific/Auckland,AKL,NZAA,I,NaN,...,2120,UL2120,ALK2120,NaN,malaysia airlines,mh,mas,132.0,mh132,mas132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2025-07-05,active,NaN,NaN,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,...,7702,UA7702,UAL7702,NaN,singapore airlines,sq,sia,944.0,sq944,sia944
96,2025-07-05,active,NaN,NaN,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,...,8089,SK8089,SAS8089,NaN,singapore airlines,sq,sia,944.0,sq944,sia944
97,2025-07-05,active,NaN,NaN,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,...,9072,GA9072,GIA9072,NaN,singapore airlines,sq,sia,944.0,sq944,sia944
98,2025-07-05,active,NaN,NaN,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,...,8148,AI8148,AIC8148,NaN,singapore airlines,sq,sia,944.0,sq944,sia944
99,2025-07-05,active,NaN,NaN,Singapore Changi,Asia/Singapore,SIN,WSSS,1,D44,...,8328,SQ8328,SIA8328,NaN,scoot,tr,tgw,596.0,tr596,tgw596

In [44]:
data.columns

Index(['flight_date', 'flight_status', 'aircraft', 'live', 'departure_airport',
       'departure_timezone', 'departure_iata', 'departure_icao',
       'departure_terminal', 'departure_gate', 'departure_delay',
       'departure_scheduled', 'departure_estimated', 'departure_actual',
       'departure_estimated_runway', 'departure_actual_runway',
       'arrival_airport', 'arrival_timezone', 'arrival_iata', 'arrival_icao',
       'arrival_terminal', 'arrival_gate', 'arrival_baggage',
       'arrival_scheduled', 'arrival_delay', 'arrival_estimated',
       'arrival_actual', 'arrival_estimated_runway', 'arrival_actual_runway',
       'airline_name', 'airline_iata', 'airline_icao', 'flight_number',
       'flight_iata', 'flight_icao', 'flight_codeshared',
       'flight_codeshared_airline_name', 'flight_codeshared_airline_iata',
       'flight_codeshared_airline_icao', 'flight_codeshared_flight_number',
       'flight_codeshared_flight_iata', 'flight_codeshared_flight_icao'],
      dtype='object')

In [45]:
null = {c:int(data[c].isnull().sum()) for c in data.columns}
null

{'flight_date': 0,
 'flight_status': 0,
 'aircraft': 100,
 'live': 100,
 'departure_airport': 0,
 'departure_timezone': 0,
 'departure_iata': 0,
 'departure_icao': 0,
 'departure_terminal': 41,
 'departure_gate': 49,
 'departure_delay': 79,
 'departure_scheduled': 0,
 'departure_estimated': 0,
 'departure_actual': 97,
 'departure_estimated_runway': 97,
 'departure_actual_runway': 97,
 'arrival_airport': 27,
 'arrival_timezone': 27,
 'arrival_iata': 0,
 'arrival_icao': 0,
 'arrival_terminal': 12,
 'arrival_gate': 80,
 'arrival_baggage': 73,
 'arrival_scheduled': 0,
 'arrival_delay': 100,
 'arrival_estimated': 100,
 'arrival_actual': 100,
 'arrival_estimated_runway': 100,
 'arrival_actual_runway': 100,
 'airline_name': 0,
 'airline_iata': 1,
 'airline_icao': 0,
 'flight_number': 0,
 'flight_iata': 1,
 'flight_icao': 0,
 'flight_codeshared': 100,
 'flight_codeshared_airline_name': 29,
 'flight_codeshared_airline_iata': 29,
 'flight_codeshared_airline_icao': 29,
 'flight_codeshared_flight_number': 29,
 'flight_codeshared_flight_iata': 29,
 'flight_codeshared_flight_icao': 29}

In [46]:
data.drop([c for c in null if null[c] == 100], axis=1,inplace=True)
data

,flight_date,flight_status,departure_airport,departure_timezone,departure_iata,departure_icao,departure_terminal,departure_gate,departure_delay,departure_scheduled,...,airline_icao,flight_number,flight_iata,flight_icao,flight_codeshared_airline_name,flight_codeshared_airline_iata,flight_codeshared_airline_icao,flight_codeshared_flight_number,flight_codeshared_flight_iata,flight_codeshared_flight_icao
0,2025-07-06,scheduled,Tontouta,Pacific/Noumea,NOU,NWWW,NaN,NaN,NaN,2025-07-06T00:55:00+00:00,...,HFY,740,5K740,HFY740,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-07-06,scheduled,Tontouta,Pacific/Noumea,NOU,NWWW,NaN,NaN,NaN,2025-07-06T00:55:00+00:00,...,AFR,4022,AF4022,AFR4022,hi fly,5k,hfy,740.0,5k740,hfy740
2,2025-07-06,scheduled,Auckland International,Pacific/Auckland,AKL,NZAA,I,NaN,NaN,2025-07-06T00:25:00+00:00,...,MAS,132,MH132,MAS132,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-07-06,scheduled,Auckland International,Pacific/Auckland,AKL,NZAA,I,NaN,NaN,2025-07-06T00:25:00+00:00,...,OMA,5585,WY5585,OMA5585,malaysia airlines,mh,mas,132.0,mh132,mas132
4,2025-07-06,scheduled,Auckland International,Pacific/Auckland,AKL,NZAA,I,NaN,NaN,2025-07-06T00:25:00+00:00,...,ALK,2120,UL2120,ALK2120,malaysia airlines,mh,mas,132.0,mh132,mas132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,NaN,2025-07-05T16:10:00+00:00,...,UAL,7702,UA7702,UAL7702,singapore airlines,sq,sia,944.0,sq944,sia944
96,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,NaN,2025-07-05T16:10:00+00:00,...,SAS,8089,SK8089,SAS8089,singapore airlines,sq,sia,944.0,sq944,sia944
97,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,NaN,2025-07-05T16:10:00+00:00,...,GIA,9072,GA9072,GIA9072,singapore airlines,sq,sia,944.0,sq944,sia944
98,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,NaN,2025-07-05T16:10:00+00:00,...,AIC,8148,AI8148,AIC8148,singapore airlines,sq,sia,944.0,sq944,sia944
99,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,1,D44,NaN,2025-07-05T16:05:00+00:00,...,SIA,8328,SQ8328,SIA8328,scoot,tr,tgw,596.0,tr596,tgw596

In [47]:
data.columns

Index(['flight_date', 'flight_status', 'departure_airport',
       'departure_timezone', 'departure_iata', 'departure_icao',
       'departure_terminal', 'departure_gate', 'departure_delay',
       'departure_scheduled', 'departure_estimated', 'departure_actual',
       'departure_estimated_runway', 'departure_actual_runway',
       'arrival_airport', 'arrival_timezone', 'arrival_iata', 'arrival_icao',
       'arrival_terminal', 'arrival_gate', 'arrival_baggage',
       'arrival_scheduled', 'airline_name', 'airline_iata', 'airline_icao',
       'flight_number', 'flight_iata', 'flight_icao',
       'flight_codeshared_airline_name', 'flight_codeshared_airline_iata',
       'flight_codeshared_airline_icao', 'flight_codeshared_flight_number',
       'flight_codeshared_flight_iata', 'flight_codeshared_flight_icao'],
      dtype='object')

In [48]:
data.drop_duplicates(inplace=True)
data

,flight_date,flight_status,departure_airport,departure_timezone,departure_iata,departure_icao,departure_terminal,departure_gate,departure_delay,departure_scheduled,...,airline_icao,flight_number,flight_iata,flight_icao,flight_codeshared_airline_name,flight_codeshared_airline_iata,flight_codeshared_airline_icao,flight_codeshared_flight_number,flight_codeshared_flight_iata,flight_codeshared_flight_icao
0,2025-07-06,scheduled,Tontouta,Pacific/Noumea,NOU,NWWW,NaN,NaN,NaN,2025-07-06T00:55:00+00:00,...,HFY,740,5K740,HFY740,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-07-06,scheduled,Tontouta,Pacific/Noumea,NOU,NWWW,NaN,NaN,NaN,2025-07-06T00:55:00+00:00,...,AFR,4022,AF4022,AFR4022,hi fly,5k,hfy,740.0,5k740,hfy740
2,2025-07-06,scheduled,Auckland International,Pacific/Auckland,AKL,NZAA,I,NaN,NaN,2025-07-06T00:25:00+00:00,...,MAS,132,MH132,MAS132,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-07-06,scheduled,Auckland International,Pacific/Auckland,AKL,NZAA,I,NaN,NaN,2025-07-06T00:25:00+00:00,...,OMA,5585,WY5585,OMA5585,malaysia airlines,mh,mas,132.0,mh132,mas132
4,2025-07-06,scheduled,Auckland International,Pacific/Auckland,AKL,NZAA,I,NaN,NaN,2025-07-06T00:25:00+00:00,...,ALK,2120,UL2120,ALK2120,malaysia airlines,mh,mas,132.0,mh132,mas132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,NaN,2025-07-05T16:10:00+00:00,...,UAL,7702,UA7702,UAL7702,singapore airlines,sq,sia,944.0,sq944,sia944
96,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,NaN,2025-07-05T16:10:00+00:00,...,SAS,8089,SK8089,SAS8089,singapore airlines,sq,sia,944.0,sq944,sia944
97,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,NaN,2025-07-05T16:10:00+00:00,...,GIA,9072,GA9072,GIA9072,singapore airlines,sq,sia,944.0,sq944,sia944
98,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,NaN,2025-07-05T16:10:00+00:00,...,AIC,8148,AI8148,AIC8148,singapore airlines,sq,sia,944.0,sq944,sia944
99,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,1,D44,NaN,2025-07-05T16:05:00+00:00,...,SIA,8328,SQ8328,SIA8328,scoot,tr,tgw,596.0,tr596,tgw596

------------------------------------------

Date Formating

In [49]:
datetime_columns = [
    'departure_scheduled',
    'departure_estimated',
    'departure_actual',
    'departure_estimated_runway',
    'departure_actual_runway',
    'arrival_scheduled',
    'flight_date'
    ]
data[datetime_columns] = data[datetime_columns].apply(pd.to_datetime, errors='coerce')

Calculating flight duration from the difference between arrival and departure

In [50]:
data['flight_duration'] = np.where(
    data['arrival_scheduled'] > data['departure_scheduled'],# condition of duration
    (data['arrival_scheduled'] - data['departure_scheduled']).dt.total_seconds()/3600, # true
    (data['departure_scheduled'] - data['arrival_scheduled']).dt.total_seconds()/3600 # false
)
data['flight_duration'] = data['flight_duration'].fillna(data['flight_duration'].mean())

-------------------------------------

Filiing null values for Status columns and IDs

In [51]:
column = 'flight_status'
data[column] = data[column].fillna("unknown")
data

,flight_date,flight_status,departure_airport,departure_timezone,departure_iata,departure_icao,departure_terminal,departure_gate,departure_delay,departure_scheduled,...,flight_number,flight_iata,flight_icao,flight_codeshared_airline_name,flight_codeshared_airline_iata,flight_codeshared_airline_icao,flight_codeshared_flight_number,flight_codeshared_flight_iata,flight_codeshared_flight_icao,flight_duration
0,2025-07-06,scheduled,Tontouta,Pacific/Noumea,NOU,NWWW,NaN,NaN,NaN,2025-07-06 00:55:00+00:00,...,740,5K740,HFY740,NaN,NaN,NaN,NaN,NaN,NaN,6.333333
1,2025-07-06,scheduled,Tontouta,Pacific/Noumea,NOU,NWWW,NaN,NaN,NaN,2025-07-06 00:55:00+00:00,...,4022,AF4022,AFR4022,hi fly,5k,hfy,740.0,5k740,hfy740,6.333333
2,2025-07-06,scheduled,Auckland International,Pacific/Auckland,AKL,NZAA,I,NaN,NaN,2025-07-06 00:25:00+00:00,...,132,MH132,MAS132,NaN,NaN,NaN,NaN,NaN,NaN,7.500000
3,2025-07-06,scheduled,Auckland International,Pacific/Auckland,AKL,NZAA,I,NaN,NaN,2025-07-06 00:25:00+00:00,...,5585,WY5585,OMA5585,malaysia airlines,mh,mas,132.0,mh132,mas132,7.500000
4,2025-07-06,scheduled,Auckland International,Pacific/Auckland,AKL,NZAA,I,NaN,NaN,2025-07-06 00:25:00+00:00,...,2120,UL2120,ALK2120,malaysia airlines,mh,mas,132.0,mh132,mas132,7.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,NaN,2025-07-05 16:10:00+00:00,...,7702,UA7702,UAL7702,singapore airlines,sq,sia,944.0,sq944,sia944,2.666667
96,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,NaN,2025-07-05 16:10:00+00:00,...,8089,SK8089,SAS8089,singapore airlines,sq,sia,944.0,sq944,sia944,2.666667
97,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,NaN,2025-07-05 16:10:00+00:00,...,9072,GA9072,GIA9072,singapore airlines,sq,sia,944.0,sq944,sia944,2.666667
98,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,NaN,2025-07-05 16:10:00+00:00,...,8148,AI8148,AIC8148,singapore airlines,sq,sia,944.0,sq944,sia944,2.666667
99,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,1,D44,NaN,2025-07-05 16:05:00+00:00,...,8328,SQ8328,SIA8328,scoot,tr,tgw,596.0,tr596,tgw596,4.500000

Filiing null values for Origin/Destination Airport Columns

In [52]:
columns = ['departure_terminal','arrival_terminal','departure_gate','arrival_gate','arrival_baggage']
data[columns] = data[columns].fillna("unknown")
data

,flight_date,flight_status,departure_airport,departure_timezone,departure_iata,departure_icao,departure_terminal,departure_gate,departure_delay,departure_scheduled,...,flight_number,flight_iata,flight_icao,flight_codeshared_airline_name,flight_codeshared_airline_iata,flight_codeshared_airline_icao,flight_codeshared_flight_number,flight_codeshared_flight_iata,flight_codeshared_flight_icao,flight_duration
0,2025-07-06,scheduled,Tontouta,Pacific/Noumea,NOU,NWWW,unknown,unknown,NaN,2025-07-06 00:55:00+00:00,...,740,5K740,HFY740,NaN,NaN,NaN,NaN,NaN,NaN,6.333333
1,2025-07-06,scheduled,Tontouta,Pacific/Noumea,NOU,NWWW,unknown,unknown,NaN,2025-07-06 00:55:00+00:00,...,4022,AF4022,AFR4022,hi fly,5k,hfy,740.0,5k740,hfy740,6.333333
2,2025-07-06,scheduled,Auckland International,Pacific/Auckland,AKL,NZAA,I,unknown,NaN,2025-07-06 00:25:00+00:00,...,132,MH132,MAS132,NaN,NaN,NaN,NaN,NaN,NaN,7.500000
3,2025-07-06,scheduled,Auckland International,Pacific/Auckland,AKL,NZAA,I,unknown,NaN,2025-07-06 00:25:00+00:00,...,5585,WY5585,OMA5585,malaysia airlines,mh,mas,132.0,mh132,mas132,7.500000
4,2025-07-06,scheduled,Auckland International,Pacific/Auckland,AKL,NZAA,I,unknown,NaN,2025-07-06 00:25:00+00:00,...,2120,UL2120,ALK2120,malaysia airlines,mh,mas,132.0,mh132,mas132,7.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,NaN,2025-07-05 16:10:00+00:00,...,7702,UA7702,UAL7702,singapore airlines,sq,sia,944.0,sq944,sia944,2.666667
96,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,NaN,2025-07-05 16:10:00+00:00,...,8089,SK8089,SAS8089,singapore airlines,sq,sia,944.0,sq944,sia944,2.666667
97,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,NaN,2025-07-05 16:10:00+00:00,...,9072,GA9072,GIA9072,singapore airlines,sq,sia,944.0,sq944,sia944,2.666667
98,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,NaN,2025-07-05 16:10:00+00:00,...,8148,AI8148,AIC8148,singapore airlines,sq,sia,944.0,sq944,sia944,2.666667
99,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,1,D44,NaN,2025-07-05 16:05:00+00:00,...,8328,SQ8328,SIA8328,scoot,tr,tgw,596.0,tr596,tgw596,4.500000

Filling null values for Delays

In [53]:
column = 'departure_delay'
data[column] = data[column].fillna(0) # i assumed that null means 0 beacause there is a lot of null field
data

,flight_date,flight_status,departure_airport,departure_timezone,departure_iata,departure_icao,departure_terminal,departure_gate,departure_delay,departure_scheduled,...,flight_number,flight_iata,flight_icao,flight_codeshared_airline_name,flight_codeshared_airline_iata,flight_codeshared_airline_icao,flight_codeshared_flight_number,flight_codeshared_flight_iata,flight_codeshared_flight_icao,flight_duration
0,2025-07-06,scheduled,Tontouta,Pacific/Noumea,NOU,NWWW,unknown,unknown,0.0,2025-07-06 00:55:00+00:00,...,740,5K740,HFY740,NaN,NaN,NaN,NaN,NaN,NaN,6.333333
1,2025-07-06,scheduled,Tontouta,Pacific/Noumea,NOU,NWWW,unknown,unknown,0.0,2025-07-06 00:55:00+00:00,...,4022,AF4022,AFR4022,hi fly,5k,hfy,740.0,5k740,hfy740,6.333333
2,2025-07-06,scheduled,Auckland International,Pacific/Auckland,AKL,NZAA,I,unknown,0.0,2025-07-06 00:25:00+00:00,...,132,MH132,MAS132,NaN,NaN,NaN,NaN,NaN,NaN,7.500000
3,2025-07-06,scheduled,Auckland International,Pacific/Auckland,AKL,NZAA,I,unknown,0.0,2025-07-06 00:25:00+00:00,...,5585,WY5585,OMA5585,malaysia airlines,mh,mas,132.0,mh132,mas132,7.500000
4,2025-07-06,scheduled,Auckland International,Pacific/Auckland,AKL,NZAA,I,unknown,0.0,2025-07-06 00:25:00+00:00,...,2120,UL2120,ALK2120,malaysia airlines,mh,mas,132.0,mh132,mas132,7.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,0.0,2025-07-05 16:10:00+00:00,...,7702,UA7702,UAL7702,singapore airlines,sq,sia,944.0,sq944,sia944,2.666667
96,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,0.0,2025-07-05 16:10:00+00:00,...,8089,SK8089,SAS8089,singapore airlines,sq,sia,944.0,sq944,sia944,2.666667
97,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,0.0,2025-07-05 16:10:00+00:00,...,9072,GA9072,GIA9072,singapore airlines,sq,sia,944.0,sq944,sia944,2.666667
98,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,0.0,2025-07-05 16:10:00+00:00,...,8148,AI8148,AIC8148,singapore airlines,sq,sia,944.0,sq944,sia944,2.666667
99,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,1,D44,0.0,2025-07-05 16:05:00+00:00,...,8328,SQ8328,SIA8328,scoot,tr,tgw,596.0,tr596,tgw596,4.500000

Filling null values for departure_actual when active --> with departure_scheduled and when --> scheduled with 'null'

In [54]:
column = 'departure_actual'
data[column] = np.where(
    data['flight_status'] == 'active',
    data[column].fillna(data['departure_scheduled']),
    np.where(
        data['flight_status'] == 'scheduled',
        data[column].fillna('null'),
        data[column]
    )
)
data[column].head(20)

0                          null
1                          null
2                          null
3                          null
4                          null
5                          null
6                          null
7                          null
8                          null
9                          null
10                         null
11                         null
12                         null
13                         null
14                         null
15                         null
16    2025-07-05 10:21:00+00:00
17    2025-07-05 14:30:00+00:00
18    2025-07-05 14:30:00+00:00
19                         null
Name: departure_actual, dtype: object

Filling null values for departure_estimated_runway & departure_actual_runway when active --> with departure_actual and when --> scheduled with 'null'

In [55]:
column = 'departure_estimated_runway'
data[column] = np.where(
    data['flight_status'] == 'active',
    data[column].fillna(data['departure_actual']),
    np.where(
        data['flight_status'] == 'scheduled',
        data[column].fillna('null'),
        data[column]
    )
)
column5 = 'departure_actual_runway'
data[column5] = np.where(
    data['flight_status'] == 'active',
    data[column5].fillna(data['departure_actual']),
    np.where(
        data['flight_status'] == 'scheduled',
        data[column5].fillna('null'),
        data[column5]
    )
)

Filling null values for flight codeshared columns

In [56]:
columns = ['flight_codeshared_airline_name',
           'flight_codeshared_airline_iata',
           'flight_codeshared_airline_icao',
           'flight_codeshared_flight_number',
           'flight_codeshared_flight_iata',
           'flight_codeshared_flight_icao']
data[columns] = data[columns].fillna('N/A')
data

,flight_date,flight_status,departure_airport,departure_timezone,departure_iata,departure_icao,departure_terminal,departure_gate,departure_delay,departure_scheduled,...,flight_number,flight_iata,flight_icao,flight_codeshared_airline_name,flight_codeshared_airline_iata,flight_codeshared_airline_icao,flight_codeshared_flight_number,flight_codeshared_flight_iata,flight_codeshared_flight_icao,flight_duration
0,2025-07-06,scheduled,Tontouta,Pacific/Noumea,NOU,NWWW,unknown,unknown,0.0,2025-07-06 00:55:00+00:00,...,740,5K740,HFY740,N/A,N/A,N/A,N/A,N/A,N/A,6.333333
1,2025-07-06,scheduled,Tontouta,Pacific/Noumea,NOU,NWWW,unknown,unknown,0.0,2025-07-06 00:55:00+00:00,...,4022,AF4022,AFR4022,hi fly,5k,hfy,740.0,5k740,hfy740,6.333333
2,2025-07-06,scheduled,Auckland International,Pacific/Auckland,AKL,NZAA,I,unknown,0.0,2025-07-06 00:25:00+00:00,...,132,MH132,MAS132,N/A,N/A,N/A,N/A,N/A,N/A,7.500000
3,2025-07-06,scheduled,Auckland International,Pacific/Auckland,AKL,NZAA,I,unknown,0.0,2025-07-06 00:25:00+00:00,...,5585,WY5585,OMA5585,malaysia airlines,mh,mas,132.0,mh132,mas132,7.500000
4,2025-07-06,scheduled,Auckland International,Pacific/Auckland,AKL,NZAA,I,unknown,0.0,2025-07-06 00:25:00+00:00,...,2120,UL2120,ALK2120,malaysia airlines,mh,mas,132.0,mh132,mas132,7.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,0.0,2025-07-05 16:10:00+00:00,...,7702,UA7702,UAL7702,singapore airlines,sq,sia,944.0,sq944,sia944,2.666667
96,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,0.0,2025-07-05 16:10:00+00:00,...,8089,SK8089,SAS8089,singapore airlines,sq,sia,944.0,sq944,sia944,2.666667
97,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,0.0,2025-07-05 16:10:00+00:00,...,9072,GA9072,GIA9072,singapore airlines,sq,sia,944.0,sq944,sia944,2.666667
98,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,2,E26,0.0,2025-07-05 16:10:00+00:00,...,8148,AI8148,AIC8148,singapore airlines,sq,sia,944.0,sq944,sia944,2.666667
99,2025-07-05,active,Singapore Changi,Asia/Singapore,SIN,WSSS,1,D44,0.0,2025-07-05 16:05:00+00:00,...,8328,SQ8328,SIA8328,scoot,tr,tgw,596.0,tr596,tgw596,4.500000

Filling null values for arrival_timezone with destination airport code (iata)

In [57]:
column = 'arrival_timezone'
data[column] = data[column].fillna(data['arrival_iata'])

Filling null values for 'flight_iata','flight_icao','flight_number' by flight_number if both flight_iata,flight_icao are null

In [58]:
columns = ['flight_iata','flight_icao']
column1 = 'flight_number'
column2 = 'flight_iata'
column3 = 'flight_icao'

data[column1] = data[column1].fillna(0)
data[column2] = data[column2].fillna(data[column3])
data[column3] = data[column3].fillna(data[column2])

n = data[column2].isnull().sum() + data[column3].isnull().sum()
if n != 0 :
    data[column2] = data[column2].fillna(data['flight_number'])
    data[column3] = data[column3].fillna(data['flight_number'])

Checking null leftovers

In [59]:
null = {c:int(data[c].isnull().sum()) for c in data.columns}
null

{'flight_date': 0,
 'flight_status': 0,
 'departure_airport': 0,
 'departure_timezone': 0,
 'departure_iata': 0,
 'departure_icao': 0,
 'departure_terminal': 0,
 'departure_gate': 0,
 'departure_delay': 0,
 'departure_scheduled': 0,
 'departure_estimated': 0,
 'departure_actual': 0,
 'departure_estimated_runway': 0,
 'departure_actual_runway': 0,
 'arrival_airport': 27,
 'arrival_timezone': 0,
 'arrival_iata': 0,
 'arrival_icao': 0,
 'arrival_terminal': 0,
 'arrival_gate': 0,
 'arrival_baggage': 0,
 'arrival_scheduled': 0,
 'airline_name': 0,
 'airline_iata': 1,
 'airline_icao': 0,
 'flight_number': 0,
 'flight_iata': 0,
 'flight_icao': 0,
 'flight_codeshared_airline_name': 0,
 'flight_codeshared_airline_iata': 0,
 'flight_codeshared_airline_icao': 0,
 'flight_codeshared_flight_number': 0,
 'flight_codeshared_flight_iata': 0,
 'flight_codeshared_flight_icao': 0,
 'flight_duration': 0}

Filling rest of null values

In [60]:
column = 'arrival_airport'
data[column] = data[column].fillna(data['flight_number'])

In [61]:
column2 = 'airline_iata'
column3 = 'airline_icao'

data[column2] = data[column2].fillna(data[column3])
data[column3] = data[column3].fillna(data[column2])
n = data[column2].isnull().sum() + data[column3].isnull().sum()
if n != 0 :
    data[column2] = data[column2].fillna(data['airline_name'])
    data[column3] = data[column3].fillna(data['airline_name'])

-------------------------------------------------------------------

------------------------------------------------------------------

Using pyOD-->IForest model for understanding departure_delay outliers in outlier column

In [62]:
column = 'departure_delay'
model = IForest()
model.fit(data[[column]].values)
outlier_labels = model.predict(data[[column]].values)
data['outlier'] = outlier_labels
data['outlier'] = data['outlier'].astype(bool)

In [63]:
column = 'flight_duration'
model = IForest()
model.fit(data[[column]].values)
outlier_labels = model.predict(data[[column]].values)
data['flight_duration_outlier'] = outlier_labels
data['flight_duration_outlier'] = data['flight_duration_outlier'].astype(bool)

In [64]:
data = data.rename(columns={'outlier':'delay_outlier'})

In [65]:
data.to_csv("..//database//transformed_data//transformed_data.csv", encoding="utf-8" ,index=False)

-------------------------------------------------------

--------------------------------------------------

Making Tables Data As .csv

airlines Table

In [66]:
columns = ['airline_name','airline_iata','airline_icao']
airlines = data[columns]
airlines = airlines.rename(columns={'airline_name':'name','airline_iata':'iata_code','airline_icao':'icao_code'})
# airlines = airlines.drop(index=0)
airlines.to_csv('..//database//tables_data//airlines.csv', encoding="utf-8" ,index=False)

airports Table

In [67]:
columns = ['departure_airport','departure_iata','departure_icao','departure_timezone']
airports = data[columns]
airports = airports.rename(columns={'departure_airport':'name','departure_iata':'iata_code','departure_icao':'icao_code','departure_timezone':'timezone'})
airports.to_csv('..//database//tables_data//airports.csv', encoding="utf-8" ,index=False)

PermissionError: [Errno 13] Permission denied: '..//database//tables_data//airports.csv'

flights Table

In [ ]:
columns = ['flight_date','flight_status','flight_number','flight_iata','flight_icao','flight_duration','delay_outlier','flight_duration_outlier']
airports = data[columns]
airports.to_csv('..//database//tables_data//flights.csv', encoding="utf-8" ,index=False)

departure_detail Table

In [70]:
columns = ['departure_gate','departure_terminal','departure_delay','departure_scheduled','departure_estimated','departure_actual','departure_estimated_runway','departure_actual_runway']
departure_detail = data[columns]
rename = {'departure_gate':'gate',
          'departure_terminal':'terminal',
          'departure_delay':'delay',
          'departure_scheduled':'scheduled',
          'departure_estimated':'estimated',
          'departure_actual':'actual',
          'departure_estimated_runway':'estimated_runway',
          'departure_actual_runway':'actual_runway'
          }
departure_detail = departure_detail.rename(columns= rename)
departure_detail.to_csv('..//database//tables_data//departure_detail.csv', encoding="utf-8" ,index=False)
departure_detail

,gate,terminal,delay,scheduled,estimated,actual,estimated_runway,actual_runway
0,unknown,unknown,0.0,2025-07-06 00:55:00+00:00,2025-07-06 00:55:00+00:00,null,null,null
1,unknown,unknown,0.0,2025-07-06 00:55:00+00:00,2025-07-06 00:55:00+00:00,null,null,null
2,unknown,I,0.0,2025-07-06 00:25:00+00:00,2025-07-06 00:25:00+00:00,null,null,null
3,unknown,I,0.0,2025-07-06 00:25:00+00:00,2025-07-06 00:25:00+00:00,null,null,null
4,unknown,I,0.0,2025-07-06 00:25:00+00:00,2025-07-06 00:25:00+00:00,null,null,null
...,...,...,...,...,...,...,...,...
95,E26,2,0.0,2025-07-05 16:10:00+00:00,2025-07-05 16:10:00+00:00,2025-07-05 16:10:00+00:00,2025-07-05 16:10:00+00:00,2025-07-05 16:10:00+00:00
96,E26,2,0.0,2025-07-05 16:10:00+00:00,2025-07-05 16:10:00+00:00,2025-07-05 16:10:00+00:00,2025-07-05 16:10:00+00:00,2025-07-05 16:10:00+00:00
97,E26,2,0.0,2025-07-05 16:10:00+00:00,2025-07-05 16:10:00+00:00,2025-07-05 16:10:00+00:00,2025-07-05 16:10:00+00:00,2025-07-05 16:10:00+00:00
98,E26,2,0.0,2025-07-05 16:10:00+00:00,2025-07-05 16:10:00+00:00,2025-07-05 16:10:00+00:00,2025-07-05 16:10:00+00:00,2025-07-05 16:10:00+00:00
99,D44,1,0.0,2025-07-05 16:05:00+00:00,2025-07-05 16:05:00+00:00,2025-07-05 16:05:00+00:00,2025-07-05 16:05:00+00:00,2025-07-05 16:05:00+00:00

arrival Table

In [71]:
columns = ['arrival_gate','arrival_terminal','arrival_baggage','arrival_scheduled']
arrival_detail = data[columns]
rename = {'arrival_gate':'gate',
          'arrival_terminal':'terminal',
          'arrival_baggage':'baggage',
          'arrival_scheduled':'scheduled'
          }
arrival_detail = arrival_detail.rename(columns=rename)
arrival_detail.to_csv('..//database//tables_data//arrival_detail.csv', encoding="utf-8" ,index=False)